"use client";

import { useState } from "react";
import { THEMES_DATA, FUNDS_DATA } from "@/lib/data";

export default function ThemesPage() {
  const [selectedTheme, setSelectedTheme] = useState(null);

  const urgencyColor = { high: "border-red-300 bg-red-50", medium: "border-amber-300 bg-amber-50", low: "border-blue-300 bg-blue-50" };
  const urgencyBadge = { high: "bg-red-100 text-red-700", medium: "bg-amber-100 text-amber-700", low: "bg-blue-100 text-blue-700" };
  const trendIcon = { up: "📈", down: "📉", flat: "➡️" };
  const sourceIcon = { note: "📝", newsletter: "✉️", news: "📰", letter: "📄" };

  const theme = selectedTheme ? THEMES_DATA.find((t) => t.id === selectedTheme) : null;

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-gray-900">Themes</h1>
        <p className="text-sm text-gray-500 mt-1">AI-synthesized investment themes from notes, newsletters, and hedge fund letters</p>
      </div>
      <div className="p-4 bg-indigo-50 rounded-xl border border-indigo-200">
        <div className="flex items-start gap-3">
          <span className="text-xl">🤖</span>
          <div>
            <h3 className="text-sm font-semibold text-indigo-900">AI Theme Engine</h3>
            <p className="text-xs text-indigo-700 mt-1">Themes are automatically generated by analyzing patterns across your internal notes, subscribed newsletters, hedge fund investor letters, and market news. Sources are linked and updated in real time.</p>
          </div>
        </div>
      </div>
      <div className="grid grid-cols-3 gap-4">
        <div className="col-span-1 space-y-3">
          <h3 className="text-xs font-semibold text-gray-500 uppercase tracking-wide">Active Themes ({THEMES_DATA.length})</h3>
          {THEMES_DATA.map((t) => (
            <button key={t.id} onClick={() => setSelectedTheme(t.id)} className={`w-full text-left p-4 rounded-xl border transition-all ${selectedTheme === t.id ? "border-indigo-500 bg-indigo-50 shadow-sm" : "border-gray-200 bg-white hover:border-gray-300"}`}>
              <div className="flex items-start justify-between gap-2">
                <p className="text-sm font-semibold text-gray-900 leading-snug">{t.name}</p>
                <span className="text-base flex-shrink-0">{trendIcon[t.trend]}</span>
              </div>
              <div className="flex items-center gap-2 mt-2">
                <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${urgencyBadge[t.urgency]}`}>{t.urgency}</span>
                <span className="text-xs text-gray-400">{t.sources.length} sources</span>
                <span className="text-xs text-gray-400">· {t.relatedFunds.length} funds</span>
              </div>
            </button>
          ))}
        </div>
        <div className="col-span-2">
          {theme ? (
            <div className="space-y-4">
              <div className={`rounded-xl border p-6 ${urgencyColor[theme.urgency]}`}>
                <div className="flex items-start justify-between">
                  <div>
                    <div className="flex items-center gap-2 mb-1">
                      <span className="text-lg">{trendIcon[theme.trend]}</span>
                      <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${urgencyBadge[theme.urgency]}`}>{theme.urgency} priority</span>
                    </div>
                    <h2 className="text-xl font-bold text-gray-900">{theme.name}</h2>
                  </div>
                </div>
                <p className="text-sm text-gray-700 mt-3 leading-relaxed">{theme.summary}</p>
              </div>
              <div className="bg-white rounded-xl border border-gray-200 p-5">
                <h3 className="text-sm font-semibold text-gray-700 mb-3">📂 Linked Sources</h3>
                <div className="space-y-2">
                  {theme.sources.map((s, i) => (
                    <div key={i} className="flex items-center gap-3 p-2.5 rounded-lg bg-gray-50 hover:bg-gray-100 transition-colors cursor-pointer">
                      <span className="text-base">{sourceIcon[s.type]}</span>
                      <div className="flex-1 min-w-0">
                        <p className="text-sm font-medium text-gray-800 truncate">{s.title}</p>
                        <p className="text-xs text-gray-400">{s.source || s.author}{s.date ? ` · ${s.date}` : ""}</p>
                      </div>
                      <span className="text-xs px-2 py-0.5 rounded-full bg-gray-200 text-gray-600">{s.type}</span>
                    </div>
                  ))}
                </div>
              </div>
              <div className="bg-white rounded-xl border border-gray-200 p-5">
                <h3 className="text-sm font-semibold text-gray-700 mb-3">🏦 Related Funds</h3>
                <div className="flex flex-wrap gap-2">
                  {theme.relatedFunds.map((f, i) => {
                    const fund = FUNDS_DATA.find((fd) => fd.name === f);
                    return (
                      <div key={i} className="px-3 py-2 rounded-lg border border-gray-200 bg-gray-50">
                        <p className="text-xs font-medium text-gray-800">{f}</p>
                        {fund && <p className="text-xs text-gray-400 mt-0.5">YTD: <span className={fund.retYTD >= 0 ? "text-green-600" : "text-red-600"}>{fund.retYTD > 0 ? "+" : ""}{fund.retYTD}%</span> · Sharpe: {fund.sharpe.toFixed(2)}</p>}
                      </div>
                    );
                  })}
                </div>
              </div>
              <div className="bg-violet-50 rounded-xl border border-violet-200 p-5">
                <h3 className="text-sm font-semibold text-violet-900 mb-2">🤖 AI Recommendation</h3>
                <p className="text-sm text-violet-800 leading-relaxed">{theme.aiInsight}</p>
              </div>
            </div>
          ) : (
            <div className="bg-white rounded-xl border border-gray-200 p-6 text-center py-24 text-gray-400">
              <p className="text-4xl mb-3">🧠</p>
              <p className="text-sm">Select a theme to explore linked sources and AI insights</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
